get_lists:
  name: Get Lists
  description: Retrieve all Listonic lists.

get_items:
  name: Get Items
  description: Retrieve items from a list.
  fields:
    list_id:
      required: true
      example: "123456789"
      selector:
        text:

add_item:
  name: Add Item
  description: Add an item to a list.
  fields:
    list_id:
      required: true
      selector:
        text:
    name:
      required: true
      selector:
        text:

delete_items:
  name: Delete Items
  description: Delete one or more items from a list.
  fields:
    list_id:
      required: true
      selector:
        text:
    ids:
      required: true
      example: [12345, 67890]
      selector:
        object:

update_item:
  name: Update Item
  description: Update an item in a list.
  fields:
    list_id:
      required: true
      selector:
        text:
    id:
      required: true
      selector:
        number:
    name:
      required: false
      selector:
        text:
    checked:
      required: false
      selector:
        boolean:

refresh_data:
  name: Refresh Data
  description: Manually refresh Listonic data to sync with the app
  
create_list:
  name: Create List
  description: Create a new Listonic list.
  fields:
    name:
      required: true
      selector:
        text:

delete_list:
  name: Delete List
  description: Delete a Listonic list.
  fields:
    list_id:
      required: true
      selector:
        text:

update_list:
  name: Update List
  description: Update a Listonic list's name.
  fields:
    list_id:
      required: true
      selector:
        text:
    name:
      required: true
      selector:
        text:
